# Generated by Django 4.0 on 2021-12-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=200)),
                ('question_2', models.CharField(max_length=200)),
                ('question_3', models.CharField(max_length=200)),
                ('question_4', models.CharField(max_length=200)),
            ],
        ),
    ]
