# Generated by Django 4.0 on 2021-12-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnmodules', '0002_remove_question_question_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_1',
            new_name='answer_1_right_one',
        ),
    ]
