# Generated by Django 4.0 on 2022-01-13 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_questionstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstat',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.question'),
        ),
    ]
