# Generated by Django 4.0 on 2022-01-17 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('game', '0004_alter_questionstat_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='', max_length=350)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=650)),
                ('answer_1_right_one', models.CharField(default='', max_length=400)),
                ('answer_2', models.CharField(default='', max_length=400)),
                ('answer_3', models.CharField(default='', max_length=400)),
                ('answer_4', models.CharField(default='', max_length=400)),
                ('game_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game.playergame')),
            ],
        ),
    ]
