# Generated by Django 4.0 on 2022-01-18 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_playergame_playerquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergame',
            name='user',
        ),
        migrations.AddField(
            model_name='playergame',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
