# Generated by Django 4.0 on 2022-01-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('game', '0006_remove_playergame_user_playergame_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergame',
            name='question',
        ),
        migrations.AddField(
            model_name='playergame',
            name='question',
            field=models.ManyToManyField(to='game.Question'),
        ),
        migrations.RemoveField(
            model_name='playergame',
            name='user',
        ),
        migrations.AddField(
            model_name='playergame',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
