# Generated by Django 4.0 on 2022-01-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_playergame_question_playergame_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_1',
            new_name='question',
        ),
        migrations.DeleteModel(
            name='PlayerQuestion',
        ),
    ]
