# Generated by Django 4.0 on 2022-01-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_rename_question_1_question_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='game_mode',
            field=models.CharField(default='elmc', max_length=150),
        ),
    ]
